kornelski/rust-rgb

src/internal/convert.rs, src/internal/ops.rs, src/internal/pixel.rs, src/internal/rgb.rs, src/internal/rgba.rs, src/lib.rs
This crate would be great for my use case, except that it is ``#[no_std]``. Given its simplicity, I was surprised that ``#[no_std]`` wasn't already supported, so I tried to add it... and it was amazingly easy.
Perhaps too easy. I am still learning the details of ``#[no_std]`` crates, so any feedback is welcome.
=> Added no_std support

src/internal/convert/array.rs, src/internal/convert/mod.rs
This seemed like a useful idea for interop with some other crates (i.e. `gltf`). Note the `Copy` trait bound on the `From` `impl`s; I could work around that requirement with some `unsafe` code, but it seems potentially cleaner to wait for NLL to land since it will supposedly provide a safe way to destructure the array.
=> Implement conversions to/from fixed-size arrays

src/internal/convert/array.rs, src/internal/rgba.rs
I think this should do it, at least assuming that moving `new()` into `impl_rgba!` doesn't have unforeseen consequences.
=> Add new() impl for BGRA

src/internal/rgb.rs
I'm used to dealing with colors in hex format, and it seems like this is a pretty small addition to make it easier to convert between them
=> Implement UpperHex and LowerHex for RGB and BGR

src/internal/ops.rs, src/lib.rs
This PR resolves https://github.com/kornelski/rust-rgb/issues/11. It implements AddAssign, SubAssign, and MulAssign for RGB and RGBA, as well as introduces a large number of new tests (sanity checks) for these methods
=> Implement AddAssign, SubAssign, and MulAssign along with associated tests

src/lib.rs
Hey there, I found it a little confusing at first as I tried to figure out how to convert my pixels into bytes partly because I didn't realize I had to import the `ComponentBytes` trait. Hopefully this minor addition to the documentation will help others, too. :slightly_smiling_face:
=> Add Use Statements to Docstring Example

Cargo.toml
Serde by [default](https://serde.rs/no-std.html) enables the `std` feature. Declaring `default-features = false` fixes this, enabling `no_std` usage.
=> enable the use of Serde in no_std environments

src/internal/convert/mod.rs, src/internal/rgba.rs
This is to close #44 which I opened earlier today. Since I wrote new tests that depended on `argb` feature, I also fixed compilation errors when `cargo test`ing with it enabled.
=> Add more conversions for `argb` types

src/internal/convert/mod.rs
Going through `as_ptr` does not give write provenance
since it creates an intermediary shared reference.
=> Go through `as_mut_ptr` instead of `as_ptr` to mutate

src/lib.rs
I spotted this typo while looking through the code to get to know the API.
=> Spotted a typo

src/internal/convert/mod.rs
https://miri.saethlin.dev/logs/rgb/0.8.35.html
=> ARGB/ABGR pixels are 4 bytes each, not 2

Cargo.toml, src/abgr.rs, src/lib.rs, src/pixel.rs, src/rgba.rs
Is my usage of `core::mem::transmute()` safe here? I couldn't find non-unsafe way of doing this.
If this is okay then I'll add implementations for the other Pixel types.
=> Add Pixel Trait and first implementation.

src/abgr.rs, src/pixel.rs, src/rgba.rs
This is an important change for the generic use of a pixel type since the `N` parameter is a leaky abstraction that should be inherent to each particular pixel.
This PR fixes that using another generic associated type for storing the fixed compile-time sized array type.
The drawback is that since we no-longer know the array size in the trait itself we can't provide default implementations, but I don't think that's much of a drawback as they are easy enough to implement on each type, especially with macros in case it gets repetitive like in `0.8`.
=> Associated array length rather than generic.

src/formats/mod.rs
Fleshes out the macro in `formats/mod.rs` to implement all of the traits on the pixel types that are in `v0.8` the only ones I've left out are: `bytemuck` traits as they will be added in a separate module which can be enabled optionally (I'll make another PR for this) and `FromIterator` which is not a valid implementation as `FromIterator` is not supposed to panic which it will do in `v0.8` (this means I'll add it in the `legacy` module when I get around to that PR).
It also adds an extra `Div` and `DivAssign` impl which were missing from `v0.8` for some reason so I though I'd add them for consistency with the other `ops` traits.
=> More inherent trait impls

Cargo.toml, src/pixel/het_pixel.rs, src/pixel/hom_pixel.rs, src/pixel/pixel_component.rs
I think I've changed my mind regarding using `num-traits`, I think it's better to offer the minimal number of trait bounds on the two `Pixel` traits and the `PixelComponent` trait since if a user requires those behaviours then they can always bound their functions with `num-traits` but on the other hand if a user has a type that does not implement one of those behaviours they cannot ever implement `HomPixel` or `HetPixel` even if they could provide all of the relevant methods. It also saves us a dependency as you mentioned.
I've also added a `IntoIterator` super-trait bound to `HomPixel` since that is a relevant trait that should never not be able to be implemented.
=> Minimal Trait Bounds + `IntoIterator` trait bound

Cargo.toml, src/formats/mod.rs, src/from.rs, src/lib.rs, src/num_traits.rs, src/pixel/arraylike.rs, src/pixel/gain_alpha.rs, src/pixel/has_alpha.rs, src/pixel/het_pixel.rs, src/pixel/hom_pixel.rs
Optionally adds implementations of the `Checked{Add,Sub..}` traits from `num-traits` as opposed to doing it manually via inherent methods as in `v0.8` which means it can be used generically unlike the inherent methods.
I also refactored the normal inherent macro a bit and switched all the glob imports to normal imports.
The dependencies now all have `default-features = false` as well.
=> `num-traits` strikes back!

src/formats/abgr.rs, src/formats/argb.rs, src/formats/bgr.rs, src/formats/bgra.rs, src/formats/gray.rs, src/formats/gray_a.rs, src/formats/grb.rs, src/formats/rgb.rs, src/formats/rgba.rs, src/pixel/arraylike.rs, src/pixel/has_alpha.rs, src/pixel/het_pixel.rs, src/pixel/hom_pixel.rs
To be reviewed after #96
Although not strictly necessary the `mut` methods are quite convenient and possibly more efficient in some scenarios depending on how well the compiler optimizes certain operations these are convenient for.
=> mut-methods

README.md, src/pixel/arraylike.rs, src/pixel/gain_alpha.rs, src/pixel/has_alpha.rs, src/pixel/het_pixel.rs, src/pixel/hom_pixel.rs, src/pixel/pixel_component.rs
One non-doctest related change was reverting back to `ColorArray` and `ComponentArray` associated types which was found to be more flexible than the `-> impl ArrayLike` return type as it lets the compiler figure out conditional trait impls in non-generic contexts.
For example the `color_array()` doc-test compiles with the associated types version but not the `-> impl ArrayLike` version since the compiler can figure out PartialEq is implemented on the  first version but not the second:
```rust
use rgb::{HetPixel, Rgb, Rgba};
let rgb = Rgb {r: 0_u8, g: 10, b: 100};
let rgba = Rgba {r: 0_u8, g: 10, b: 100, a: 50};
assert_eq!(rgb.color_array(), [0, 10, 100]);
assert_eq!(rgba.color_array(), [0, 10, 100]);
```
I also added an implementation of `PixelComponent` for `bool` which would possibly be …
=> Add doc examples to everything and reword normal docs.

src/bytemuck.rs, src/formats/mod.rs, src/formats/rgbw.rs, src/lib.rs, src/num_traits.rs, src/pixel/het_pixel.rs, src/pixel/hom_pixel.rs
Fixes #21 
One concern I have when implementing the `Rgbw` pixel type is what `From<>` implementations to add since converting to `Rgb` and `Bgr` seems possible but could be lossy since the white component would be lost which could change the color quite drastically whereas all the other current `From` conversions simply change the memory layout of the same components.
For this reason I have not added any `From` conversions with the existing pixel types.
=> Add `Rgbw` pixel

README.md, src/formats/abgr.rs, src/formats/argb.rs, src/formats/bgr.rs, src/formats/bgra.rs, src/formats/grb.rs, src/formats/luma.rs, src/formats/luma_a.rs, src/formats/rgb.rs, src/formats/rgba.rs, src/formats/rgbw.rs
Adds a doc-test for each pixel type to show an initialization example, and a short section in the readme about using `bytemuck`.
=> More doc-tests and bytemuck section in the `README.md`

Cargo.toml, README.md, examples/example.rs, src/bytemuck.rs, src/core_traits.rs, src/formats/gray.rs, src/formats/gray_a.rs, src/formats/gray_alpha.rs, src/from.rs, src/inherent_impls.rs, src/legacy/internal/convert/mod.rs, src/legacy/internal/ops.rs, src/legacy/internal/pixel.rs, src/legacy/internal/rgba.rs, src/legacy/mod.rs, src/lib.rs, src/num_traits.rs, src/pixel_traits/gain_alpha.rs, src/pixel_traits/has_alpha.rs, src/pixel_traits/het_pixel.rs, src/pixel_traits/pixel.rs, src/tuples.rs
Now this branch *should* be completely backwards compatible with the current `v0.8` branch.
It would be nice if cargo had the ability to force all dependencies to use a custom version of a dependency which would let us test this manually on popular crates without making an actual release.
=> remove legacy feature

src/formats/gray.rs
Should fix the only major backwards compatibility issue from the testing in #129
=> revert the `Deref` impl for `Gray_v08`

README.md, src/pixel_traits/arraylike.rs, src/pixel_traits/het_pixel.rs
To match `Pixel::to_array()` and `Pixel::each_mut()` for slightly better consistency.
=> rename `color_array` and `color_array_mut` to `to_color_array` and `each_color_mut`

src/bytemuck_impl.rs, src/formats/gray_alpha44.rs, src/lib.rs
I am working on drawing app using slint framework on my raspbery pi pico 2. I need to allocate slint pixelbuffer where user can draw, but i am limited to 8 bit per pixel (because of device memory limit) and i need to store both grayscale and alpha values per pixel. slint uses `rgb` library for its buffers so i decided to contribute the feature direcly to this repo. I failed to make this type generic like all other format types in the repo. sorry). Also many trait impls can not be applied to my type like to others because of its binary nature.
=> GrayAlpha44 type added (4 bits for gray and 4 bit for alpha)
